---
- name: Install Deluge
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "deluge-daemon"
    - "deluge-web"

- name: Template Deluge Config
  become: true
  template:
    src: "core.conf.j2"
    dest: "/var/lib/deluge/.config/deluge/core.conf"

- name: Enable and Start Deluge Service
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - "deluge-daemon"
    - "deluge-web"