---
- name: Install 'nginx'
  become: true
  package:
    name: nginx
    state: present

- name: Configure 'httpd_can_network_connect' SELinux Policy
  become: true
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Copy Certificates
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/"
    owner: "root"
    group: "nginx"
    mode: "0640"
  loop:
    - "ssl/titanium-server.crt"
    - "ssl/titanium-server.key"

- name: Copy 'nginx' Config
  become: true
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart nginx

- name: Copy 'nginx' SSL Config
  become: true
  copy:
    src: "ssl.conf"
    dest: "/etc/nginx/ssl.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart nginx

- name: Copy 'nginx' Proxy Config
  become: true
  copy:
    src: "proxy.conf"
    dest: "/etc/nginx/proxy.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart nginx

# https://github.com/linuxserver/reverse-proxy-confs
- name: Copy Subdomain Configs
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item | basename }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_fileglob: conf.d/*.conf
  notify:
    - Restart nginx

- name: Template Subdomain Configs
  become: true
  template:
    src: "subdomain.conf"
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - name: grocy
      port: 9283
    - name: cockpit
      port: 9090
      https: true
    - name: music
      port: 4533
    - name: links
      port: 9092
    - name: rss
      port: 7273
    - name: status
      port: 3001
    - name: torrent
      port: 8112
      extra_config:
        - "add_header X-Frame-Options SAMEORIGIN;"
    - name: jellyfin
      port: 8096
      extra_config:
        - "proxy_set_header Range $http_range;"
        - "proxy_set_header If-Range $http_if_range;"
      extra_locations:
        - "~ (/jellyfin)?/socket"
  notify:
    Restart nginx

- name: Enable and Start 'nginx' Service
  become: true
  systemd:
    name: "nginx"
    enabled: true
    state: started
