---
- name: Install 'nginx'
  become: true
  dnf:
    name: nginx
    state: present

- name: Configure 'httpd_can_network_connect' SELinux Policy
  become: true
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Copy Certificates
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/"
    owner: "root"
    group: "nginx"
    mode: "0640"
  loop:
    - "ssl/titanium-server.crt"
    - "ssl/titanium-server.key"

- name: Copy 'nginx' Config
  become: true
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart nginx

- name: Copy 'nginx' SSL Config
  become: true
  copy:
    src: "ssl.conf"
    dest: "/etc/nginx/ssl.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart nginx

- name: Copy 'nginx' Proxy Config
  become: true
  copy:
    src: "proxy.conf"
    dest: "/etc/nginx/proxy.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart nginx

# https://github.com/linuxserver/reverse-proxy-confs
- name: Copy Subdomain Configs
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item | basename }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_fileglob: conf.d/*.conf
  notify:
    - Restart nginx

- name: Enable and Start 'nginx' Service
  become: true
  systemd:
    name: "nginx"
    enabled: true
    state: started
