---
title: "Dashboard"
subtitle: "Titanium-Server"
footer: ""

services:
  - items:
    - name: "Cockpit"
      icon: "fab fa-fedora"
      url: "https://cockpit.titanium-server.lan"
    - name: "Jellyfin"
      icon: "fas fa-play-circle"
      url: "https://jellyfin.titanium-server.lan"
    - name: "Torrents"
      icon: "fas fa-download"
      url: "https://torrent.titanium-server.lan"
    - name: "RSS"
      icon: "fas fa-rss"
      url: "https://rss.titanium-server.lan"
    - name: "Music"
      icon: "fas fa-headphones"
      url: "https://music.titanium-server.lan"
    - name: "Prowlarr"
      icon: "fas fa-download"
      url: "https://prowlarr.titanium-server.lan"
    - name: "Radarr"
      icon: "fas fa-file-video"
      url: "https://radarr.titanium-server.lan"
    - name: "Sonarr"
      icon: "fas fa-file-video"
      url: "https://sonarr.titanium-server.lan"
