---
- hosts: all
  tasks:
  - name: Update Packages
    become: true
    dnf:
      name: "*"
      state: latest

- hosts: all
  roles:
    - podman
    - firewall
    - samba
    - nginx
    - cockpit
    - deluge
    - miniflux
    - prowlarr
    - radarr
    - sonarr
    - name: containers
      tags: containers

