---
- hosts: all
  tasks:
  - name: Update Packages
    become: true
    dnf:
      name: "*"
      state: latest

- hosts: vm
  roles:
    - vm

- hosts: all
  roles:
    - firewall
    - nginx
    - cockpit
    - transmission
    - podman
    - jellyfin
    - homer