---
- hosts: all
  name: Configure Server
  roles:
    - upgrade
    - podman
    - firewall
    - samba
    - role: nginx
      tags: containers
    - cockpit
    - deluge
    - role: containers
      tags: containers
