---
- hosts: all
  tasks:
  - name: Update Packages
    become: true
    dnf:
      name: "*"
      state: latest

- hosts: vm
  roles:
    - vm

- hosts: all
  roles:
    - podman
    - firewall
    - samba
    - nginx
    - homer
    - cockpit
    - deluge
    - jellyfin
    - miniflux
    - navidrome
    - ombi
    - prowlarr
    - radarr
    - sonarr
    - linkding
    - uptime-kuma
