---
- hosts: vm
  tasks:
  - name: Ensure Packages are Up-to-Date
    become: true
    dnf:
      name: "*"
      state: latest

  - name: Ensure 'Fedora Server Edition' Group is installed
    become: true
    dnf:
      name: "@Fedora Server Edition"
      state: present

  - name: Ensure Storage Directory Exists
    become: true
    file:
      path: /storage
      state: directory

- hosts: all
  roles:
    - firewall
    - nginx
    - transmission
