---
- name: Update Packages
  become: true
  dnf:
    name: "*"
    state: latest

- name: Install Fedora Server Edition Group
  become: true
  dnf:
    name: "@Fedora Server Edition"
    state: present
