---
- name: Install 'Fedora Server Edition' Group
  become: true
  dnf:
    name: "@Fedora Server Edition"
    state: present

- name: Create 'storage' Group
  become: true
  group:
    name: "storage"
    state: present

- name: Add '{{ ansible_user_id }}' Groups
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - "wheel"
      - "storage"
    append: true

- name: Set Password for '{{ ansible_user_id }}'
  become: true
  user:
    name: "{{ ansible_user_id }}"
    password: "$6$o4Y5wSr/WTlymO/M$WlBwCYoZF28WFbWqeojzfhejsJd9K06VcPikA2O6OFV99n5/mQOLZiT35cjKpVXdUQJysfpY/w8tiDn0WkJi9/"

- name: Create Storage Directory
  become: true
  file:
    path: /storage
    state: directory
    group: "storage"
    mode: 0775

- name: Create Storage->Media Directory
  become: true
  file:
    path: /storage/media
    state: directory
    group: "storage"
    mode: 0775
