---
- name: Install 'Fedora Server Edition' Group
  become: true
  dnf:
    name: "@Fedora Server Edition"
    state: present

- name: Add '{{ ansible_user_id }}' to 'wheel' Group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - "wheel"
    append: true

- name: Create 'storage' Group
  become: true
  group:
    name: "storage"
    state: present

- name: Add '{{ ansible_user_id }}' to 'storage' Group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - "storage"
    append: true

- name: Create Storage Directory
  become: true
  file:
    path: /storage
    state: directory
    group: "storage"
    mode: 0775

- name: Create Storage->Media Directory
  become: true
  file:
    path: /storage/media
    state: directory
    group: "storage"
    mode: 0775
