---
- name: Create 'navidrome' Container Storage
  become: true
  file:
    path: "/storage/containers/navidrome"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0775

- name: Create 'navidrome' Container
  vars:
    container_name: "navidrome"
    image: "docker.io/deluan/navidrome"
    tag: "latest"
    ports:
      - host: "4533"
        container: "4533"
    mounts:
      - "/storage/containers/navidrome/:/data"
      - "/storage/media/Music:/music"
  include_role:
    name: container
