---
- name: Create 'nextcloud' Container Storage
  become: true
  file:
    path: "/storage/containers/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0775
  with_items:
    - "nextcloud"
    - "nextcloud/config"
    - "nextcloud/data"

- name: Create 'nextcloud' Container
  vars:
    container_name: "nextcloud"
    image: "lscr.io/linuxserver/nextcloud"
    tag: "latest"
    ports:
      - host: "7443"
        container: "443"
    env_vars:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=America/Toronto"
    mounts:
      - "/storage/containers/nextcloud/config:/config"
      - "/storage/containers/nextcloud/data:/data"
  include_role:
    name: container