---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/tmp/kuma: z
  labels:
    io.containers.autoupdate: registry
  name: uptime-kuma-pod
spec:
  containers:
  - image: docker.io/louislam/uptime-kuma:latest
    name: uptime-kuma
    ports:
    - containerPort: 3001
      hostPort: 3001
    volumeMounts:
    - mountPath: /app/data
      name: data
  volumes:
  - name: data
    hostPath:
      path: /storage/containers/uptime-kuma
      type: Directory
