---
# TODO: Rename tasks for include container_name for output

- name: Create Storage Directory for Container
  become: true
  file:
    path: "/storage/containers/{{ container_name }}"
    state: directory
    owner: "podman"
    group: "storage"
    mode: 0775

- name: Template Systemd Unit
  template:
    src: "container.service.j2"
    dest: "~/.config/systemd/user/podman-{{ container_name }}.service"

- name: Start and Enable Systemd Unit
  systemd:
    name: "podman-{{ container_name }}"
    enabled: true
    state: started
    scope: user
