---
- name: Install 'podman'
  become: true
  package:
    name: "podman"
    state: present

- name: Add 'podman' User
  become: true
  user:
    name: "podman"
    system: true
    home: "/var/lib/podman"

- name: Enable Systemd Lingering for Podman
  become: true
  command:
    cmd: loginctl enable-linger podman
    creates: "/var/lib/systemd/linger/podman"

- name: Create Storage->Containers Directory
  become: true
  file:
    path: /storage/containers
    state: directory
    group: "storage"
    mode: 0775
