---
- name: Install 'podman'
  become: true
  package:
    name: "podman"
    state: present

- name: Enable Systemd Lingering for '{{ ansible_user_id }}'
  become: true
  command:
    cmd: "loginctl enable-linger {{ ansible_user_id }}"
    creates: "/var/lib/systemd/linger/{{ ansible_user_id }}"

- name: Create '{{ ansible_user_id }}' Systemd User Directory
  file:
    path: "~/.config/systemd/user"
    state: directory

- name: Create Storage->Containers Directory
  become: true
  file:
    path: "/storage/containers"
    state: directory
    group: "storage"
    mode: 0775
