---
- name: Install 'podman'
  become: true
  package:
    name: "podman"
    state: present

- name: Add 'podman' User
  become: true
  user:
    name: "podman"
    system: true
    home: "/var/lib/podman"

- name: Create Storage->Containers Directory
  become: true
  file:
    path: /storage/containers
    state: directory
    group: "storage"
    mode: "u=rwx,g=rwx,o=r"
