---
- name: Install Transmission
  become: true
  package:
    name: transmission-daemon
    state: present

- name: Configure rmem_max
  become: true
  sysctl:
    name: "net.core.rmem_max"
    value: "4194304"
    state: present

- name: Configure wmem_max
  become: true
  sysctl:
    name: "net.core.wmem_max"
    value: "1048576"
    state: present

- name: Create Transmission Config Directory
  become: true
  file:
    path: /var/lib/transmission/.config/transmission-daemon
    state: directory
    owner: transmission
    group: transmission

- name: Configure Transmission
  become: true
  copy:
    src: settings.json
    dest: /var/lib/transmission/.config/transmission-daemon/settings.json
    owner: transmission
    group: transmission
    mode: 0600

- name: Enable and Start Transmission Service
  become: true
  systemd:
    name: transmission-daemon
    enabled: true
    state: started
