---
- name: Ensure Transmission is Installed
  become: true
  package:
    name: transmission-daemon
    state: present

- name: Ensure rmem_max is '4194304'
  become: true
  sysctl:
    name: "net.core.rmem_max"
    value: "4194304"
    state: present

- name: Ensure wmem_max is '1048576'
  become: true
  sysctl:
    name: "net.core.wmem_max"
    value: "1048576"
    state: present

- name: Ensure Transmission Config Directory is Created
  become: true
  file:
    path: /var/lib/transmission/.config/transmission-daemon
    state: directory
    owner: transmission
    group: transmission

- name: Configure Transmission
  become: true
  copy:
    src: settings.json
    dest: /var/lib/transmission/.config/transmission-daemon/settings.json
    owner: transmission
    group: transmission
    mode: 0600

- name: Ensure Transmission Service is Enabled and Started
  become: true
  systemd:
    name: transmission-daemon
    enabled: true
    state: started
