---
- name: Ensure Transmission is Installed
  become: true
  package:
    name: transmission-daemon
    state: present

- name: Ensure rmem_max is '4194304'
  become: true
  sysctl:
    name: "net.core.rmem_max"
    value: "4194304"
    state: present

- name: Ensure wmem_max is '1048576'
  become: true
  sysctl:
    name: "net.core.wmem_max"
    value: "1048576"
    state: present

- name: Ensure Transmission Service is Enabled and Started
  become: true
  systemd:
    name: transmission-daemon
    enabled: true
    state: started
