---
- name: Install firewalld Python Bindings
  become: true
  package:
    name: python3-firewall
    state: present

- name: Start and Enable firewalld Service
  become: true
  systemd:
    name: firewalld
    enabled: true
    state: started

- name: Permit Traffic for HTTP
  become: true
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: Permit Traffic for Transmission
  become: true
  firewalld:
    port: 9091/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Permit Traffic for Jellyfin
  become: true
  firewalld:
    port: 8096/tcp
    permanent: true
    immediate: true
    state: enabled
