---
- name: Install firewalld Python Bindings
  become: true
  package:
    name: python3-firewall
    state: present

- name: Start and Enable firewalld Service
  become: true
  systemd:
    name: firewalld
    enabled: true
    state: started

- name: Create Allow Rules for Services
  become: true
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http

- name: Create Allow Rules for Ports
  become: true
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 9091
    - 8096
