---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: flatnotes
spec:
  containers:
    - image: docker.io/dullage/flatnotes:latest
      name: flatnotes
      env:
        - name: FLATNOTES_AUTH_TYPE
          value: password
        - name: FLATNOTES_USERNAME
          value: tryton
        - name: FLATNOTES_PASSWORD
          value: test
        - name: FLATNOTES_SECRET_KEY
          value: test
      ports:
        - containerPort: 8080
          hostPort: 6464
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath:
        path: /storage/containers/flatnotes
        type: Directory
