---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: jellyfin
spec:
  containers:
    - image: ghcr.io/linuxserver/jellyfin:latest
      name: jellyfin
      env:
        - name: PUID
          value: 0
        - name: PGID
          value: 0
        - name: TZ
          value: America/Toronto
      ports:
        - containerPort: 8096
          hostPort: 8096
      volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
  volumes:
    - name: config
      hostPath:
        path: /storage/containers/jellyfin/config
        type: DirectoryOrCreate
    - name: data
      hostPath:
        path: /storage/media
        type: Directory
