---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: miniflux
spec:
  containers:
    - name: miniflux
      image: docker.io/miniflux/miniflux:latest
      ports:
        - containerPort: 8080
          hostPort: 7273
      env:
        - name: DATABASE_URL
          value: postgres://miniflux:miniflux@localhost/miniflux?sslmode=disable
        - name: RUN_MIGRATIONS
          value: 1
        - name: CREATE_ADMIN
          value: 1
        - name: ADMIN_USERNAME
          value: admin
        - name: ADMIN_PASSWORD
          value: "{{ miniflux_admin_password }}"
    - name: db
      image: docker.io/postgres:14-alpine
      env:
        - name: POSTGRES_USER
          value: miniflux
        - name: POSTGRES_PASSWORD
          value: miniflux
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
  volumes:
    - name: data
      hostPath:
        path: /storage/containers/miniflux
        type: Directory
