---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: navidrome
spec:
  containers:
    - image: docker.io/deluan/navidrome:latest
      name: navidrome
      env:
        - name: ND_SCANNER_SCHEDULE
          value: "@monthly"
        - name: ND_PROMETHEUS_ENABLED
          value: "true"
        - name: ND_SPOTIFY_ID
          value: "{{ navidrome_spotify_client_id }}"
        - name: ND_SPOTIFY_SECRET
          value: "{{ navidrome_spotify_client_secret }}"
      ports:
        - containerPort: 4533
          hostPort: 4533
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /music
          name: music
          readOnly: true
  volumes:
    - name: data
      hostPath:
        path: /storage/containers/navidrome/data
        type: DirectoryOrCreate
    - name: music
      hostPath:
        path: /storage/media/Music
        type: Directory
