---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: navidrome
spec:
  containers:
    - image: deluan/navidrome:latest
      name: navidrome
      env:
        - name: ND_SCANSCHEDULE
          value: "@hourly"
        - name: ND_PROMETHEUS_ENABLED
          value: "true"
      ports:
        - containerPort: 4533
          hostPort: 4533
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /music
          name: music
          readOnly: true
  volumes:
    - name: data
      hostPath:
        path: /storage/containers/navidrome
        type: Directory
    - name: music
      hostPath:
        path: /storage/media/Music
        type: Directory
