---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: nextcloud
spec:
  containers:
    - name: nextcloud
      image: docker.io/nextcloud:latest
      ports:
        - containerPort: 80
          hostPort: 3443
      env:
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
      volumeMounts:
        - mountPath: /var/www/html
          name: data
        - mountPath: /tmp
          name: tmp
    - name: db
      image: docker.io/postgres:15-alpine
      env:
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: nextcloud
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db
  volumes:
    - name: data
      hostPath:
        path: /storage/containers/nextcloud/data
        type: Directory
    - name: db
      hostPath:
        path: /storage/containers/nextcloud/db
        type: Directory
    - name: tmp
      hostPath:
        path: /storage/containers/nextcloud/tmp
        type: Directory
