---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: prowlarr
spec:
  containers:
    - image: ghcr.io/linuxserver/prowlarr:latest
      name: prowlarr
      env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: America/Toronto
      ports:
        - containerPort: 9696
          hostPort: 9696
      volumeMounts:
        - mountPath: /config
          name: config
  volumes:
    - name: config
      hostPath:
        path: /storage/containers/prowlarr/config
        type: DirectoryOrCreate
