---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/storage/containers/radarr: z
    bind-mount-options:/storage/media: z
  labels:
    io.containers.autoupdate: registry
  name: radarr
spec:
  containers:
    - image: ghcr.io/linuxserver/radarr:latest
      name: radarr
      env:
        - name: PUID
          value: 0
        - name: PGID
          value: 0
        - name: TZ
          value: America/Toronto
      ports:
        - containerPort: 7878
          hostPort: 7878
      volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
  volumes:
    - name: config
      hostPath:
        path: /storage/containers/radarr
        type: Directory
    - name: data
      hostPath:
        path: /storage/media
        type: Directory
