---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: romm
spec:
  containers:
    - image: docker.io/zurdi15/romm:latest
      name: romm
      env:
        - name: IGDB_CLIENT_ID
          value: "{{ romm_igdb_client_id }}"
        - name: IGDB_CLIENT_SECRET
          value: "{{ romm_igdb_client_secret }}"
        - name: STEAMGRIDDB_API_KEY
          value: "{{ romm_steam_grid_api_key }}"
      ports:
        - containerPort: 80
          hostPort: 16610
      volumeMounts:
        - mountPath: /romm/resources
          name: resources
        - mountPath: /romm/database
          name: database
        - name: config
          mountPath: /romm/config.yml
          subPath: config.yaml
        - mountPath: /romm/library:ro
          name: roms
  volumes:
    - name: resources
      hostPath:
        path: /storage/containers/romm/resources
        type: Directory
    - name: database
      hostPath:
        path: /storage/containers/romm/database
        type: Directory
    - name: config
      configMap:
        name: romm
    - name: roms
      hostPath:
        path: /storage/media/Roms
        type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: romm
data:
  config.yaml: ""
