---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/storage/containers/sonarr: z
    bind-mount-options:/storage/media: z
  labels:
    io.containers.autoupdate: registry
  name: sonarr
spec:
  containers:
    - image: ghcr.io/linuxserver/sonarr:develop
      name: sonarr
      env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: America/Toronto
      ports:
        - containerPort: 8989
          hostPort: 8989
      volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
  volumes:
    - name: config
      hostPath:
        path: /storage/containers/sonarr
        type: Directory
    - name: data
      hostPath:
        path: /storage/media
        type: Directory
