---
- name: Create Kube Directory
  file:
    path: "/storage/containers/kube"
    state: directory

- name: Create Container Systemd Directory
  file:
    path: "~/.config/containers/systemd"
    state: directory

- name: Copy Kube Yaml Files
  copy:
    src: "kube/{{ item }}.yaml"
    dest: "/storage/containers/kube/{{ item }}.yaml"
  loop:
    - homer

- name: Template Systemd Kube Units
  template:
    src: "service.kube.j2"
    dest: "~/.config/containers/systemd/{{ item }}.kube"
  loop:
    - homer

- name: Start Systemd Kube Units
  systemd:
    name: "{{ item }}"
    daemon-reload: true
    state: started
    scope: user
  loop:
    - homer
