---
- name: Create Container Storage Directories
  become: true
  file:
    path: "/storage/containers/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0775
  with_items:
    - "jellyfin"
    - "miniflux"

- name: Create Kube Directory
  file:
    path: "/storage/containers/kube"
    state: directory

- name: Create Container Systemd Directory
  file:
    path: "~/.config/containers/systemd"
    state: directory

- name: Template Kube Yaml Files
  template:
    src: "kube/{{ item }}.yaml"
    dest: "/storage/containers/kube/{{ item }}.yaml"
  loop: "{{ container_services }}"

- name: Template Systemd Kube Units
  template:
    src: "service.kube.j2"
    dest: "~/.config/containers/systemd/{{ item }}.kube"
  loop: "{{ container_services }}"

- name: Start Systemd Kube Units
  systemd:
    name: "{{ item }}"
    daemon-reload: true
    state: started
    scope: user
  loop: "{{ container_services }}"
