---
- name: Create Container Storage Volumes
  become: true
  file:
    path: "/storage/containers/{{ item | basename | splitext | first }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0775
  with_fileglob: "kubes/*.yaml"

- name: Create Kube Directory
  file:
    path: "~/.config/kubes"
    state: directory

- name: Copy Kube Deployments
  copy:
    src: "{{ item }}"
    dest: "~/.config/kubes/{{ item | basename }}"
  with_fileglob: "kubes/*.yaml"

- name: Template Systemd Unit
  template:
    src: "container.service.j2"
    dest: "~/.config/systemd/user/container@.service"

- name: Enable Systemd Units
  systemd:
    name: "container@{{ item | basename | splitext | first }}"
    daemon-reload: true
    enabled: true
    state: started
    scope: user
  with_fileglob: "kubes/*.yaml"
