---
- name: Create Container Storage Directories
  become: true
  ansible.builtin.file:
    path: "/storage/containers/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0775"
    setype: container_file_t
  loop: "{{ container_services }}"

- name: Create Kube Directory
  ansible.builtin.file:
    path: "/storage/containers/kube"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0744"

- name: Create Container Systemd Directory
  ansible.builtin.file:
    path: "~/.config/containers/systemd"
    state: directory
    mode: "0755"

- name: Template Kube Yaml Files
  ansible.builtin.template:
    src: "kube/{{ item }}.yaml"
    dest: "/storage/containers/kube/{{ item }}.yaml"
    mode: "0644"
  loop: "{{ container_services }}"

- name: Template Systemd Kube Units
  ansible.builtin.template:
    src: "service.kube.j2"
    dest: "~/.config/containers/systemd/{{ item }}.kube"
    mode: "0644"
  loop: "{{ container_services }}"

- name: Start Systemd Kube Units
  ansible.builtin.systemd:
    name: "{{ item }}"
    daemon-reload: true
    state: started
    scope: user
  loop: "{{ container_services }}"
