---
apiVersion: v1
kind: Pod
metadata:
  labels:
    io.containers.autoupdate: registry
  name: homer
spec:
  containers:
  - image: docker.io/b4bz/homer:latest
    name: homer
    ports:
    - containerPort: 8080
      hostPort: 8095
    volumeMounts:
    - mountPath: /www/assets/config.yml
      name: config
  volumes:
  - name: config
    hostPath:
      path: /storage/containers/homer/config.yaml
      type: File
