---
- name: Ensure firewalld Python Bindings are Installed
  become: true
  package:
    name: python3-firewall
    state: present

- name: Permit Traffic for HTTP
  become: true
  firewalld:
    service: http
    permanent: true
    state: enabled
  register: rule

- name: Permit Traffic for Transmission
  become: true
  firewalld:
    port: 9091/tcp
    permanent: true
    state: enabled
  register: rule

- name: Permit Traffic for Jellyfin
  become: true
  firewalld:
    port: 8096/tcp
    permanent: true
    state: enabled
  register: rule

- name: Restart firewalld on Rule Changes
  become: true
  systemd:
    name: firewalld
    state: reloaded
  when: rule.changed
