---
- name: Install firewalld python bindings
  become: true
  package:
    name: python3-firewall
    state: present

- name: Open port for HTTP
  become: true
  firewalld:
    service: http
    permanent: true
    state: enabled
  register: rule

- name: Open port for Transmission
  become: true
  firewalld:
    port: 9091/tcp
    permanent: true
    state: enabled
  register: rule

- name: Open port for Jellyfin
  become: true
  firewalld:
    port: 8096/tcp
    permanent: true
    state: enabled
  register: rule

- name: Restart firewalld
  become: true
  systemd:
    name: firewalld
    state: reloaded
  when: rule.changed
